import { TeamMember } from './types';

export const SEED_MEMBERS: TeamMember[] = [
  {
    id: "seed_1",
    name: "Farhad",
    projectName: "tailiu604",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-13",
    projectValue: 360,
    pageCount: 6,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://tailiu604.wpsvaomega.com",
    progress: 0,
    themeColor: "purple"
  },
  {
    id: "seed_2",
    name: "AbuBakar",
    projectName: "kauaiconsulting",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-09",
    projectValue: 160,
    pageCount: 3,
    profileName: "code_wonders_Fiverr",
    projectUrl: "https://thinkertrading.com/",
    progress: 0,
    themeColor: "blue"
  },
  {
    id: "seed_3",
    name: "Abu Bakar",
    projectName: "knwsllc",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-12",
    projectValue: 400,
    pageCount: 5,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://knwsllc.softvenceprime.com/",
    progress: 0,
    themeColor: "emerald"
  },
  {
    id: "seed_4",
    name: "Redwan",
    projectName: "bbreliable",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-12",
    projectValue: 200,
    pageCount: 4,
    profileName: "star_edge_",
    projectUrl: "https://bbreliable.softvenceomega.com/",
    progress: 0,
    themeColor: "rose"
  },
  {
    id: "seed_5",
    name: "Sobuj",
    projectName: "kyliew",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-15",
    projectValue: 300,
    pageCount: 8,
    profileName: "twisbit_Fiverr",
    projectUrl: "https://kyliew.softvenceprime.com",
    progress: 0,
    themeColor: "amber"
  },
  {
    id: "seed_6",
    name: "Santo",
    projectName: "kyliew",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-15",
    projectValue: 300,
    pageCount: 8,
    profileName: "twisbit_Fiverr",
    projectUrl: "https://kyliew.softvenceprime.com/",
    progress: 0,
    themeColor: "purple"
  },
  {
    id: "seed_7",
    name: "Redwan",
    projectName: "kuebraasik",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-11",
    projectValue: 160,
    pageCount: 4,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://dimgrey-parrot-299157.hostingersite.com",
    progress: 0,
    themeColor: "blue"
  },
  {
    id: "seed_8",
    name: "Shakil",
    projectName: "mojtabavahid",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-21",
    projectValue: 296,
    pageCount: 5,
    profileName: "star_edge_",
    projectUrl: "https://demo.com",
    progress: 0,
    themeColor: "emerald"
  },
  {
    id: "seed_9",
    name: "Jahid",
    projectName: "wart1n",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-14",
    projectValue: 183.2,
    pageCount: 5,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://ravance.fr/",
    progress: 0,
    themeColor: "rose"
  },
  {
    id: "seed_10",
    name: "Farhad",
    projectName: "heatherlakiesha",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-14",
    projectValue: 120,
    pageCount: 1,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://heatherlakiesha.softvenceomega.com",
    progress: 0,
    themeColor: "amber"
  },
  {
    id: "seed_11",
    name: "Abu Bakar",
    projectName: "delvinarsan",
    assignedDate: "2026-02-28",
    deliveryDate: "2026-03-09",
    projectValue: 316,
    pageCount: 5,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://delvinarsan2.softvenceprime.com/",
    progress: 0,
    themeColor: "purple"
  },
  {
    id: "seed_12",
    name: "Imran",
    projectName: "emmanuelanazia",
    assignedDate: "2026-01-16",
    deliveryDate: "2026-03-29",
    projectValue: 240,
    pageCount: 5,
    profileName: "lamp_tech_Fiverr",
    projectUrl: "https://playsafe1.wpsvaomega.com/",
    progress: 0,
    themeColor: "blue"
  },
  {
    id: "seed_13",
    name: "Shakil",
    projectName: "polenography",
    assignedDate: "2026-03-03",
    deliveryDate: "2026-03-13",
    projectValue: 240,
    pageCount: 4,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://polenography.softvenceomega.com",
    progress: 0,
    themeColor: "emerald"
  },
  {
    id: "seed_14",
    name: "Jahid",
    projectName: "blushing123",
    assignedDate: "2026-03-03",
    deliveryDate: "2026-03-10",
    projectValue: 144,
    pageCount: 3,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://beltonhopeproject.softvenceomega.com",
    progress: 0,
    themeColor: "rose"
  },
  {
    id: "seed_15",
    name: "Farhad",
    projectName: "mohamedl123",
    assignedDate: "2026-03-03",
    deliveryDate: "2026-03-13",
    projectValue: 216,
    pageCount: 5,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://mohamedl.softvenceomega.com",
    progress: 0,
    themeColor: "amber"
  },
  {
    id: "seed_16",
    name: "Tofajjal",
    projectName: "flodelmundo",
    assignedDate: "2026-03-03",
    deliveryDate: "2026-03-15",
    projectValue: 440,
    pageCount: 10,
    profileName: "twisbit_Fiverr",
    projectUrl: "https://softvenceomega.com/",
    progress: 0,
    themeColor: "purple"
  },
  {
    id: "seed_17",
    name: "Sobuj",
    projectName: "arkeeskitchen",
    assignedDate: "2026-02-04",
    deliveryDate: "2026-03-14",
    projectValue: 396,
    pageCount: 5,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://chefrosie.softvenceomega.com/",
    progress: 0,
    themeColor: "blue"
  },
  {
    id: "seed_18",
    name: "Redwan",
    projectName: "giacomo9722",
    assignedDate: "2026-03-04",
    deliveryDate: "2026-03-14",
    projectValue: 160,
    pageCount: 5,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://giacomo9722.softvenceomega.com/",
    progress: 0,
    themeColor: "emerald"
  },
  {
    id: "seed_19",
    name: "Oli",
    projectName: "mashpotatox",
    assignedDate: "2026-03-04",
    deliveryDate: "2026-03-22",
    projectValue: 560,
    pageCount: 10,
    profileName: "intel_hub_Fiverr",
    projectUrl: "https://demo.com",
    progress: 0,
    themeColor: "rose"
  },
  {
    id: "seed_20",
    name: "Sobuj",
    projectName: "jwjonesmd",
    assignedDate: "2026-03-07",
    deliveryDate: "2026-03-19",
    projectValue: 320,
    pageCount: 10,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://demo.com",
    progress: 0,
    themeColor: "amber"
  },
  {
    id: "seed_21",
    name: "Imran",
    projectName: "jwjonesmd",
    assignedDate: "2026-03-07",
    deliveryDate: "2026-03-19",
    projectValue: 320,
    pageCount: 10,
    profileName: "shopify_manir_Fiverr",
    projectUrl: "https://demo.com",
    progress: 0,
    themeColor: "purple"
  }
];
